name: Ahorcado CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run unittests
      run: python ahorcado-back/ahorcado_unittests.py
    
    - name: Generate Code Coverage Report
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        coverage run ahorcado-back/ahorcado_unittests.py
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2

  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Executing remote command
    uses: appleboy/ssh-action@master
    with:
    HOST: ${{ secrets.HOST }}
    USERNAME: ${{ secrets.USERNAME }}
    PORT: ${{ secrets.PORT }}
    KEY: ${{ secrets.SSHKEY }}
    PASSPHRASE: ${{ secrets.PASSPHRASE }}
    script: touch hola.txt

  sonarcloud:
      name: SonarCloud
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # runapp:
  #   name: Build application
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.x
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: Run backend
  #       shell: pwsh
  #       run: |
  #             cd ahorcado-back
  #             py run.py 
  #             python run.py 

  #     - name: Install Front-End Dependencies and run
  #       shell: pwsh
  #       run: |
  #         cd ahorcado-front
  #         npm install
  #         npm start

  
  # uitests:
  #     name: Run UI Tests
  #     runs-on: ubuntu-latest
  #     steps:
  #     - uses: actions/checkout@v3

  #     - name: Set up Python 3.x
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.x'

  #     - name: Install dependencies
  #       run: |
  #           python -m pip install --upgrade pip
  #           pip install -r requirements.txt


  #     - name: Run UI Tests
  #       shell: pwsh
  #       run: behave automation/features

      
    
      